#!/bin/sh
# Name   : gcc
# Version: March 31, 1994
# Author : James Wells
# Purpose: Boostrap "gcc"  compiler script.

#==============================================================================
# STANDARD OPTIONS
#==============================================================================

  # Modify these options to match your default compiler-compiler needs.

  compiler="${BLD_LIB}/gcc-gcc -B${BLD_LIB}/gcc- -coff"
  std_opts="-mbitfield -fsvs_bitfields -fwritable-strings -fcombine-regs"
  std_opts="$std_opts -fcaller-saves -pipe"

#==============================================================================
# GCC With 68020 and 68881 Support (DEFAULT)
#==============================================================================

  $compiler -m68020 -m68881 $std_opts $*

#==============================================================================
# GCC With 68020 Support Only
#==============================================================================

# $compiler -m68020 $std_opts $*

#==============================================================================
# GCC With 68010 Support Only
#==============================================================================

# $compiler -m68010 $std_opts $*

#==============================================================================
# End of Bootsrap GCC Compiler Script           
#==============================================================================
